### ISSUE TITLE
Gradle 2.3 appengine and eclipse not working together?

### ISSUE THREAD

**Issue by keithmarsh** [GoogleCloudPlatform/gradle-appengine-plugin#174]
With a very simple build.gradle, I get an error running gradle tasks (or anything else)
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/keith/workspace/telemetryWORK/build.gradle' line: 3

* What went wrong:
A problem occurred evaluating root project 'telemetryWORK'.
> Failed to apply plugin [id 'appengine']
   > No such property: model for class: org.gradle.plugins.ide.eclipse.EclipsePlugin

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

If I comment out either appengine or eclise, it works fine.  I'm not sure if this is an appengine issue, an eclipse issue, or a 2.3 issue.  Here's my build.gradle

```groovy
apply plugin: 'eclipse'
apply plugin: 'war'
apply plugin: 'appengine'

buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'com.google.appengine:gradle-appengine-plugin:1.9.18'
    }
}

repositories {
    mavenCentral()
}
```
and here's the stack trace.  Sorry - I don't know groovy well enough to diagnose, but it seems to be having an issue in the functional test area.

```
* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'telemetryWORK'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:154)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:59)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:492)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:86)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'appengine']
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:147)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:102)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
	at org.gradle.api.plugins.PluginAware$apply.call(Unknown Source)
	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:34)
	at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
	at build_epinryhbztrldlb6mf4e23g52.run(/home/keith/workspace/telemetryWORK/build.gradle:3)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
	... 32 more
Caused by: groovy.lang.MissingPropertyException: No such property: model for class: org.gradle.plugins.ide.eclipse.EclipsePlugin
	at com.google.appengine.AppEnginePlugin$_addEclipseConfigurationForFunctionalTestRuntimeConfiguration_closure34.doCall(AppEnginePlugin.groovy:695)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:201)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
	at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:126)
	at org.gradle.api.DomainObjectCollection$withType.call(Unknown Source)
	at com.google.appengine.AppEnginePlugin.addEclipseConfigurationForFunctionalTestRuntimeConfiguration(AppEnginePlugin.groovy:694)
	at com.google.appengine.AppEnginePlugin.this$2$addEclipseConfigurationForFunctionalTestRuntimeConfiguration(AppEnginePlugin.groovy)
	at com.google.appengine.AppEnginePlugin$this$2$addEclipseConfigurationForFunctionalTestRuntimeConfiguration$42.callCurrent(Unknown Source)
	at com.google.appengine.AppEnginePlugin.addFunctionalTestConfigurationsAndSourceSet(AppEnginePlugin.groovy:677)
	at com.google.appengine.AppEnginePlugin.this$2$addFunctionalTestConfigurationsAndSourceSet(AppEnginePlugin.groovy)
	at com.google.appengine.AppEnginePlugin$this$2$addFunctionalTestConfigurationsAndSourceSet$41.callCurrent(Unknown Source)
	at com.google.appengine.AppEnginePlugin.configureFunctionalTest(AppEnginePlugin.groovy:620)
	at com.google.appengine.AppEnginePlugin.this$2$configureFunctionalTest(AppEnginePlugin.groovy)
	at com.google.appengine.AppEnginePlugin$this$2$configureFunctionalTest$40.callCurrent(Unknown Source)
	at com.google.appengine.AppEnginePlugin.apply(AppEnginePlugin.groovy:167)
	at com.google.appengine.AppEnginePlugin.apply(AppEnginePlugin.groovy)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
	at org.gradle.api.internal.plugins.RulesCapablePluginApplicator.applyImperative(RulesCapablePluginApplicator.java:42)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:133)
	... 43 more

```

**Comment by loosebazooka** [comment]
Oh, I was under the impression that this code path was fixed. Perhaps something changed in Gradle 2.3 that I'm unaware of. I'll take a look.

I've been building against 2.1 so this is understandable.  I can only suggest you try an earlier version of Gradle (2.2/2.1) at the moment.

**Comment by loosebazooka** [comment]
Yeah so in Gradle 2.3, the Eclipse Plugin doesn't have a "model" object anymore, this breaks our plugin.  I'll have to figure out a work around.

**Comment by loosebazooka** [comment]
Can you check if this works for you? 

https://github.com/loosebazooka/gradle-appengine-plugin/tree/eclipseFix

To do a local build and test :
clone the repo
```
$ git clone https://github.com/loosebazooka/gradle-appengine-plugin.git --branch eclipseFix
```
install the snapshotted version into local maven repo
```
$ ./gradlew install snapshot (linux/mac)
$ gradlew.bat install snapshot (windows - I think)
```
then modify your appengine build file to pull in this snapshotted version of the plugin
1. add `mavenLocal()` as a buildscript depednency to your project
2. change the version of your plugin to `1.9.18-SNAPSHOT`

your build file might look like :

```
buildscript {
  repositories {
    mavenLocal()
    mavenCentral()
  }

  dependencies {
    classpath "com.google.appengine:gradle-appengine-plugin:1.9.18-SNAPSHOT"
  }
}
```

**Comment by oakstair** [comment]
The fix works for me!

**Comment by keithmarsh** [comment]
That works for me too.  Thank you.

**Comment by loosebazooka** [comment]
Nice, thanks for checking it out.  I'll do some more local testing and push it.

**Comment by loosebazooka** [comment]
I seemed to have messed up with that change on the gradle version conditional.  I'm actually a little confused it worked.  If you have a change, can you check again using the same instructions?

**Comment by keithmarsh** [comment]
Yep, working ok.

**Comment by keithmarsh** [comment]
Hello.  Is there an ETA on this fix being released?

**Comment by loosebazooka** [comment]
We're synchronized with the App Engine release cycle, this will go out with 1.9.19 (I'm not sure when that is). I can only suggest :
1. If you don't really need features in gradle 2.3, you could try with gradle 2.2.1 till that's ready. 
2. Use a local build of the plugin.

**Comment by keithmarsh** [comment]
Thanks for the info.

**Comment by shujath** [comment]
Seems that file has been removed
fatal: Remote branch eclipseFix not found in upstream origin
